[workspace]
members = ["fahrenheit_and_celsius_conversion", "fibonacci_1", "guessing_game", "hello_world", "hello_world_format", "launch_off", "ownership_lab", "random_six_dice", "string_lab"]
resolver = "3"
